export const products = [
  {
    id: 1,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-1.jpg",
    name: "Women Shoes",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 2,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-2-2.jpg",
    name: "Porto Transparent Images",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 3,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-3.jpg",
    name: "Ideapad",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 4,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-4-2.jpg",
    name: "Black Men Shoes",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 5,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-5.jpg",
    name: "Watch",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 6,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-6-2.jpg",
    name: "Woman Dress",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 7,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-7.jpg",
    name: "Black Bag",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 8,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-8.jpg",
    name: "Porto Both Sticky Info",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 9,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-9.jpg",
    name: "Glasses",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 10,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-10.jpg",
    name: "Black Men Coat",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 11,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-11.jpg",
    name: "Girl High Shoes",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
  {
    id: 12,
    img: "https://portotheme.com/html/porto_ecommerce/assets/images/demoes/demo3/products/product-12.jpg",
    name: "Girl Low Shoes",
    price: 59.00,
    discounted: 49,
    count: 0,
  },
];
